# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# Only build test master & travis
branches:
  only:
  - master
  - travis

# Enable C++ support
language: cpp

# Need MYCC and MYCXX as travis overwrites CC and CXX

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: MYCC=gcc-4.9 MYCXX=g++-4.9

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: MYCC=gcc-5 MYCXX=g++-5

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']
      env: MYCC=gcc-6 MYCXX=g++-6

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env: MYCC=gcc-7 MYCXX=g++-7

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['g++-6', 'clang-3.8']
      env: MYCC=clang-3.8 MYCXX=clang++-3.8

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-4.0']
          packages: ['g++-6', 'clang-4.0']
      env: MYCC=clang-4.0 MYCXX=clang++-4.0

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0']
          packages: ['g++-6', 'clang-5.0']
      env: MYCC=clang-5.0 MYCXX=clang++-5.0

# Build steps
script:
  - mkdir build
  - cd build
  - CC=$MYCC CXX=$MYCXX cmake -DTREAT_WARNINGS_AS_ERRORS=1 .. && make VERBOSE=1
  - ctest --output-on-failure

notifications:
  email:
    - tomi.valkeinen@iki.fi
